fix: logic inconsistency for `publish` input on nvidia-test workflow
The use of SNAP_CHANNEL as `latest/edge/runid-<RUN_ID>` only makes
sense if the checkbox to publish is marked as true.

If not it means that it needs to run against `latest/edge` but there is
no  logic handling it and the workflow fails with the error:
```
 error: requested a non-existing branch on latest/edge for snap "docker":
```
as shown here:
https://github.com/canonical/docker-snap/actions/runs/12631899123/job/35194514402#step:5:1469

Signed-off-by: Lincoln Wallace <lincoln.wallace@canonical.com>